### ISSUE TITLE
No incomming msgs from irc to discord 

### ISSUE THREAD

**Issue by haxxus** [j0ack/discirc#13]
Hello , from discord to irc everything shows perfect but nothing from irc to discord , I'm running it on a centos 7 dedicated vps ,  any recommendations ?
config being used: 

{
  "_comments": "Discord app token",
  "discordToken": "secret you shouldn't paste it here",

  "_comments": "IRC server address",
  "ircServer": "irc.quakenet.org",

  "_comments": "IRC server port",
  "ircPort": "6667",

  "_comments": "IRC SSL use",
  "ircSSl": false,

  "_comments": "IRC nick",
  "ircNick": "discirc",

  "_comments": "IRC nick password [OPTIONAL]",
  "ircPass": "MyIRCPass",

  "_comments": "Channels maps",
  "mappingChannels": {
    "gauntlet-party": "#sohva"
  },

  "_comments": "IRC channel passwords [OPTIONAL]",
  "channelPass": {
      "#irc_chan1": "ChannelPass2",
      "#irc_chan2": "ChannelPass2"
  },

  "_comments": "Command chars to not interpret",
  "commandChars": ["~", "!"]
}

**Comment by haxxus** [comment]
is it an issue on my end or possible with he bot code ?

**Comment by j0ack** [comment]
Sounds weird to me, since the message sending seems to work fine from discord to irc.

I don't know if it is a possible issue that your bot can not write in your discord buffer maybe ? I'm not very familiar with the discord's buffers possible configuration.

**Comment by haxxus** [comment]
umm neither do I, but for example I set this one with the same settings as your like token , channel id's and so on and works both ways but doesn't have all the features that yours have :( 

https://github.com/Hackndo/discord-irc-sync

 Question is does it work fine on your end have you tested it recently ?

**Comment by haxxus** [comment]
before I has centos7 python 3.6 now on debian 9 , python 3.5, same thing

**Comment by j0ack** [comment]
I just deploy the last version of the package and it works just fine for me.

I just created a [logging](https://github.com/j0ack/discirc/tree/logging) branch, you just have to add a `"debug": true` key in your config file. 
Maybe you can test it if you want.

**Comment by haxxus** [comment]
well , that's funny after adding the debug command now it works perfect both ways

**Comment by j0ack** [comment]
That's definitively weird since the code just log events. 

Could you disable the debug and told me if you encounter the same issue ?

**Comment by haxxus** [comment]
yep same issue without debug

**Comment by j0ack** [comment]
I just realized that I have changed a config line corresponding to channel pass in the logging branch.

I'm going to merge this change it in the master branch, could you test it and tell me if you still encounter the bug.

**Comment by haxxus** [comment]
Hello , sorry been busy :) , just upgraded to the new release and yes now works without debug! .  question could you include a user list command ? for example from irc ( could be privet msg from bot to client ) 
users: rolename
and the bot grabs the users inside the role name entered 

and from discord
@users ircChannelname
 displaying all the users inside the irc channel entered . 
   Would be very helpful .

**Comment by haxxus** [comment]
And were getting this error randomly sometimes it lasts 24 hours sometimes within hours , bot drops from irc with the error:

<iamsosexy__> i can show u the message
<iamsosexy__> [18:34] == discirc [~discirc@120.145.198.35.bc.googleusercontent.com] has quit [Excess Flood]
<iamsosexy__> [20:30] == discirc [~discirc@120.145.198.35.bc.googleusercontent.com] has quit [Excess Flood]
Irc-BotBOT - Today at 3:01 PM
<iamsosexy__> u just need to mention it gets dropped with an excess flood message
<iamsosexy__> and the dev may know why

**Comment by j0ack** [comment]
Hello, I will close this issue since it seems resolved with the last master version.

Concerning the last error, it seems it's concerning the IRC server which kick your bot for flood, I can't really do something about that.

Concerning your features, feel free to open a new issue on the project corresponding to it.
