### ISSUE TITLE
Reconnect after disconnect

### ISSUE THREAD

**Issue by crabctrl** [j0ack/discirc#17]
The program is disconnecting from the IRC server (Freenode) about every hour, even without any messages being sent.

Reconnecting after the connection has been lost would fix this issue.

Tested on Ubuntu Server 18.04

**Comment by j0ack** [comment]
Hi @atoms118 

Thank you for reporting this issue, which version of discirc are you using ?

**Comment by crabctrl** [comment]
I am using the Pip version (if there's a repository somewhere please link!)

Edit: It seems to be reconnecting now, I'm not sure what's up with that, and I'm not sure if it's discirc reconnecting to IRC or if it just crashed and systemd restarted it

**Comment by j0ack** [comment]
The repository is this one and the version in pip is the same.

Discirc does not reconnect it must be your systemd which restarted it.

I just pushed a new version on a new [branch](https://github.com/j0ack/discirc/pull/18). 
You need to add a `ircAutoReconnect` set to `True` in your config file.

Could you tell me if this fix your issue ?

**Comment by crabctrl** [comment]
I've installed the `fix-17` branch and set the option in my config; I'll get back to you in a few hours to see if it's working. Thanks!

**Comment by crabctrl** [comment]
Yes, the new reconnect option is working great. Thanks for the quick support!

**Comment by j0ack** [comment]
You're welcome, I'll update the new version on Pypi asap.
