### ISSUE TITLE
json doesn't do comments

### ISSUE THREAD

**Issue by TeoTwawki** [j0ack/discirc#4]
Your [example file](https://github.com/j0ack/discirc/blob/master/config-example.json#L14) will lead inexperienced users to create broken configs and then be confused as to why it isn't working. Also you have an extra comma on line 14. If you want ``//comments` you will need something to strip those out before feeding it to the json decoder.

**Comment by j0ack** [comment]
You're absolutely right. 

Would you consider to modify JSON parsing and sending me a PR ? I don't have much time implementing this right now.

**Comment by TeoTwawki** [comment]
Unfortunately I don't have a solid solution that performs well to just toss into your project. 

But what I could do is make the example file just a document quoting the json structure within, so people don't mistake it for a file they can just edit and use.

Work for you?

**Comment by j0ack** [comment]
Well I find an inelegant way to do this using a "__comment" key which will not be parsed in the config. I'll implement this asap still looking for a better solution.

**Comment by TeoTwawki** [comment]
`JSON.minify()` can do this but its _slow_. I'm not familar with other methods.
