### ISSUE TITLE
Add irc password into config

### ISSUE THREAD

**Issue by j0ack** [j0ack/discirc#6]
Create an optional config key `ircPass` to send password at irc authentication.

**Comment by TeoTwawki** [comment]
Do you mean nick pass or channel pass?

I took a stab at both recently. Had partial success.

```json
{
    "discordToken": "my_discord_token",
    "ircServer": "chat.freenode.org",
    "ircPort": "6667",
    "ircSSl": false,
    "ircNick": "torii",
    "nickPass": "password",
    "mappingChannels":
    {
        "discord_chan": "#irc_chan"
    },
    "ircKeys":
    {
        "#irc_chan": "password"
    },
    "commandChars": ["~", "!"]
}
```

**Comment by j0ack** [comment]
I was talking about nickPass but eventually I could include channel pass as well.
How about you create a new issue with it if you feel to implement it ?
