### ISSUE TITLE
Cannot identify to nickserv or join channels on rizon network (appears to work fine on freenode)

### ISSUE THREAD

**Issue by TeoTwawki** [j0ack/discirc#8]
This is beyond my knowledge of IRC protocol to diagnose and fix myself.

Rizon's `#help` channel suggested that it may be related to their first ping being sent sooner than it used to be sent (a recent change). I don't understand enough of what is going on in discirc to know the timing on these things so I can't check into that.

**Comment by j0ack** [comment]
Is it resolved with the last version of discirc ?

**Comment by TeoTwawki** [comment]
Dunno, I gave up on it 10 months ago. I'll have to pull latest and make a rizon test account
